#!/bin/bash

# ein kleiner Variablentest

echo "\$# = $#"
echo "\$0 = $0"
echo "\$1 = $1"

# sudo gphoto2 --capture-image -F 4 -I 3
# sudo gphoto2 --get-all-files
# sudo gphoto2 --capture-image-and-download -F 4 -I 3
# sudo gphoto2 --capture-image-and-download --interval 4 --frames 4 --force-overwrite --filename "raw/$1_%01n.jpg"
sudo gphoto2 --capture-image-and-download --keep --interval 4 --frames 4 --force-overwrite --filename "raw/$(date +"%d.%m.%y,%k:%m:%S")_%01n.jpg"



proc_id=$(pidof -s feh)
# feh --recursive --randomize --auto-zoom --geometry 1920x1080 -x -F -D 5 ~/Desktop/Photobox/aktuell/raw &
feh --recursive --reverse --draw-filename --auto-zoom --geometry 1920x1080 -x -F -D 5 ~/Desktop/Photobox/aktuell/raw &
sleep 3
kill $proc_id

lp -o position=bottom 16.01.16,18:01:39.jpg

sudo java -jar PhotoCombine.jar 16.01.16,18:01:39 /home/pi/Desktop/Photobox/aktuell/raw/ /home/pi/Desktop/Photobox/aktuell/raw/



exit 0